name = "vu-ai"
main = "src/worker.ts"      
compatibility_date = "2025-08-15"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_server_modules"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[env.dev]
name = "vu-ai-dev"

[env.production]
name = "vu-ai-prod"