name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    # opcional: asegura que solo se ejecute en el repo correcto
    # if: github.repository == 'ORGANIZACION/NOMBRE_REPO'

    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare
        run: |
          BRANCH="${GITHUB_REF##*/}"
          echo "Current branch: $BRANCH"

          if [ "$BRANCH" = "main" ]; then
            echo "Deploying to production..."
            wrangler deploy --env production
          else
            echo "Deploying to dev..."
            wrangler deploy --env dev
          fi
